version: '3'

services:
    database:
        image: mongo
        ports:
            - 27017:27017
        volumes:
            - ./data/db:/data/db

    server:
        build:
            context: ./
            dockerfile: ./devops/Dockerfile
        ports:
            - "8080:8080"
